Output "../gifs/normal-mode/minor-modes/view-mode/j.gif"

Set Theme "Catppuccin Mocha"
Set FontSize 17
Set Width 1200
Set Height 600

Hide
Type "helix long_demo.rs"
Enter
Type "37G"
Sleep 100ms
Show
Sleep 1000ms
Hide
Type "zj"
Sleep 100ms
Show
Sleep 300ms
Hide
Type "zj"
Sleep 100ms
Show
Sleep 300ms
Hide
Type "zj"
Sleep 100ms
Show
Sleep 300ms
Hide
Type "zj"
Sleep 100ms
Show
Sleep 300ms
Hide
Type "zj"
Sleep 100ms
Show
Sleep 2000ms
