Output "../gifs/normal-mode/minor-modes/window-mode/k.gif"

Set Theme "Catppuccin Mocha"
Set FontSize 12
Set Width 1200
Set Height 600

Hide
Type "helix first_window.rs"
Enter
Type "ge"
Type ":vs second_window.rs"
Enter
Type "ge"
Type ":hs fourth_window.rs"
Enter
Type "ge"
Ctrl+W
Type "h"
Type ":hs third_window.rs"
Enter
Type "ge"
Ctrl+W
Type "h"
Sleep 100ms
Show
Sleep 1000ms
Hide
Ctrl+W
Sleep 100ms
Type "k"
Show
Sleep 2000ms
