Output "../gifs/normal-mode/minor-modes/goto-mode/m.gif"

Set Theme "Catppuccin Mocha"
Set FontSize 17
Set Width 1200
Set Height 600
Set TypingSpeed 100ms

Hide
Type "helix ../src/main.rs"
Enter
Sleep 100ms
Show
Sleep 300ms
Type "Omod another_module;"
Escape
Sleep 300ms
Type ":w"
Enter
Sleep 1000ms
Space
Type "f"
Sleep 300ms
Type "help"
Sleep 300ms
Enter
Sleep 2000ms
Space
Type "f"
Sleep 300ms
Type "gif"
Sleep 300ms
Enter
Sleep 2000ms
Hide
Type "gm"
Sleep 100ms
Show
Sleep 2000ms
