Output "gifs/normal-mode/movement/T-l.gif"

Set Theme "Catppuccin Mocha"
Set FontSize 20
Set Width 1200
Set Height 600

Hide
Type "helix demo.rs"
Enter
Type "ge"
Sleep 100ms
Show
Sleep 1000ms
Hide
Type "T"
Show
Type "l"
Sleep 1000ms
Hide
Type "T"
Show
Type "l"
Sleep 1000ms
Hide
Type "T"
Show
Type "l"
Sleep 1000ms
Hide
Type "T"
Show
Type "l"
Sleep 1000ms
Hide
Type "T"
Show
Type "l"
Sleep 1000ms
Hide
Type "T"
Show
Type "l"
Sleep 1000ms
